# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/teammate_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server


# Security (temporarily disable for setup)
spring.security.user.name=admin
spring.security.user.password=admin

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT Configuration
jwt.secret=teammateSecretKeyForJWTTokenGenerationVeryLongAndSecure2026LicentaSabinaAlexia
jwt.expiration=86400000
server.port=${PORT:8080}

